import Dependencies._

ThisBuild / scalaVersion     := "2.13.6"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "org.exercism"
ThisBuild / organizationName := "exercism"

lazy val root = (project in file("."))
  .settings(
    name := "TestRunner",
    libraryDependencies ++= Seq(
      "org.json" % "json" % "20220320",
      monocleCore,
      monocleMacro,
      scalaTest, // not in the Test scope so that it gets added to the fat jar generated by sbt assembly
    )
  )

// TODO: update the exercise description, to make it clear that only monocle lens will compile?
//       also, solve the exercise to have a better idea of how things should work
//       https://exercism.org/tracks/scala/exercises/lens-person
